### ISSUE TITLE
Cadi hat Fragen

### ISSUE THREAD

**Issue by getSono** [EinfachGustaf/SMPClaim#2]
GuMo... ^^ Ich hab ein paar Fragen zu dem Claim-Plugin. So ne generelle Erklärung, was welcher Befehl nachher im Einzelnen alles für Folgen hat, wäre toll. 🙂

1. So weit ich es gestern mitbekommen habe, kann auf Kisten zugreifen und Dinge rausnehmen, auch wenn ein Claim drauf ist, ist das gewollt? Kann man das generell sperren und den Zugriff auf Kisten gezielt gewähren (keinen / Person xy / allgemein)?

2. Ich konnte gestern Shulker auf Chunks setzen, die jemand anderes geclaimt hat, aber nicht wieder abbauen. Das ist erst mal unpraktisch, sollte jemand unterwegs mal einen Chunk geclaimt haben, bekomme ich da ja nie wieder. 😉  Also sollte man eigene Shulker immer wieder abbauen können.
-> Daher: woran kann ich erkennen, dass ein Chunk geclaimt ist (und von wem, damit ich weiß, wen ich eventuell kontaktieren muss), damit mir das unterwegs nirgends passiert bzw. kann man das eventuell ändern?

3. Wenn man etwas setzen kann, wenn ein Chunk geclaimt ist, gilt das auch für TNT, kann man es dann auch anzünden und wenn ja, geht was kaputt, wenn es gezündet wird?

4. Kann man Team-Claims implementieren? Wenn Bases groß sind und man viele Mitglieder hat, ist das Ganze nämlich ziemlich aufwändig. Und auch da wäre es praktisch, wenn man irgendwie erkennen könnte, was schon geclaimt ist und wer alles Rechte hat.

4b. Wäre es möglich, einen Befehl einzubinden, bei dem man mehrere Chunks per Koordinaten claimen kann?

5. Kann man Co-Claimer ermöglichen? Gerade bei Teambases wie unserer wäre es ganz gut, wenn das ginge, weil ja nicht jeder immer da ist, um Rechte zu erteilen.

Ich hoffe, ich hab nix verpeilt und bin hier richtig mit meinem Krams ^^, falls nicht, bitte nicht direkt verbal verprügeln 😉

**Comment by getSono** [comment]
Ich fand das als gute Fragen und hab deswegen ein Issue geöffnet

**Comment by DinoMarlir** [comment]
Please open an issue for every feature request

**Comment by getSono** [comment]
Ok, warum wurde es wieder geöffnet?

**Comment by DasSharkk** [comment]
Sind jz alle im Issue-Tracker zu finden, dementsprechend wird dieses Issue hier geschlossen
---
1. [OP#78](https://openproject.internal.einfachgustaf.live/projects/smpclaim/work_packages/78/)
2. [OP#79](https://openproject.internal.einfachgustaf.live/projects/smpclaim/work_packages/79/)
3. [OP#75](https://openproject.internal.einfachgustaf.live/projects/smpclaim/work_packages/75/)
4. [OP#80](https://openproject.internal.einfachgustaf.live/projects/smpclaim/work_packages/80/)
4b. [OP#82](https://openproject.internal.einfachgustaf.live/projects/smpclaim/work_packages/82/)
5. [OP#83](https://openproject.internal.einfachgustaf.live/projects/smpclaim/work_packages/83/)
